# Using Go image for 1.21.6
FROM golang:1.21.6 as builder

# Set working directory
WORKDIR /app 

# Copy go modules and manifests
COPY go.mod go.sum ./
RUN go mod download

# Copy rest of source code
COPY . . 

# Build the Go app
RUN go build -o Nexus

# Create final image that is lightweight 
FROM debian:bullseye-slim

# Install runtime libs
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

# Set working directory 
WORKDIR /root/

# Copy binary from building stage
COPY --from=builder /app/Nexus .

# Expose port 
EXPOSE 8080

# Command to run application 
CMD ["./Nexus"]
