AWSTemplateFormatVersion: '2010-09-09'
Description: Deploying nexus common networking resources.

Resources:
  # Set up a VPC for networking
  NexusVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Nexus-VPC
  # First Subnet
  SubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref NexusVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs ""]
  # Second Subnet
  SubnetB:
    Type: AWS::EC2::Subnet 
    Properties:
      VpcId: !Ref NexusVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs ""]
  # Internet Gateway
  NexusInternetGateway:
    Type: AWS::EC2::InternetGateway
  # Gateway Attachment
  NexusGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref NexusVPC
      InternetGatewayId: !Ref NexusInternetGateway
  # Route Table
  NexusRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref NexusVPC
  # Set up route for route table
  NexusRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref NexusRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref NexusInternetGateway
  # Set up route assocation
  NexusRouteTableAssociationSubnetA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetA
      RouteTableId: !Ref NexusRouteTable
  # Set up route assocation
  NexusRouteTableAssociationSubnetB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetB
      RouteTableId: !Ref NexusRouteTable
  # Cluster information
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: NexusCluster
  # Set up auto scaling role
  NexusAutoScalingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: application-autoscaling.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ECSAutoScalingPolicy
          PolicyDocument: 
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - ecs:UpdateService
                  - ecs:DescribeServices
                Resource: '*'
 # Create IAM Profile for ECS tasks
  NexusInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref NexusAutoScalingRole

Outputs: 
  SubnetAId:
    Value: !Ref SubnetA
    Export:
      Name: SubnetAId
  SubnetBId:
    Value: !Ref SubnetB
    Export:
      Name: SubnetBId
  NexusCluster:
    Value: !Ref ECSCluster
    Export:
      Name: NexusCluster
  NexusAutoScalingRole:
    Value: !Ref NexusAutoScalingRole
    Export:
      Name: NexusAutoScalingRole
  NexusInstanceProfile:
    Value: !Ref NexusInstanceProfile
    Export:
      Name: NexusInstanceProfile