AWSTemplateFormatVersion: '2010-09-09'
Description: Deploying reversion service with autoscaling policies and cost-effective ec2 with asg setup.

Parameters:
  ImageURI:
    Type: String
    Description: ECR image URI for the service

Resources:  
  # Define ecs tasks for reversion
  TaskDefinitionReversion:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: ReversionTaskDefinition
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !ImportValue NexusTaskExecutionRoleArn
      ContainerDefinitions:
        - Name: ReversionContainer
          Image: !Ref ImageURI
          PortMappings:
            - ContainerPort: 80
          Environment:
            - Name: SERVICE
              Value: Reversion
            - Name: ENV
              Value: staging
            - Name: PASSPHRASE
              Value: staging/Nexus/passphrase
            - Name: REGION
              Value: us-east-2
            - Name: ENV_FILE
              Value: .env-staging.gpg

          Essential: true

  # Spin up the reversion service using EC2
  ReversionService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !ImportValue NexusCluster
      ServiceName: ReversionService
      TaskDefinition: !Ref TaskDefinitionReversion 
      DesiredCount: 1
      LaunchType: EC2
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue SubnetAId
            - !ImportValue SubnetBId
          AssignPublicIp: ENABLED

  # Launch configuration that will be associated with ASG 
  ReversionLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55955c7d316
      SecurityGroups:
        - !ImportValue DefaultSecurityGroup
      IamInstanceProfile: !ImportValue NexusInstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo ECS_CLUSTER=${NexusCluster} >> /etc/ecs/ecs.config
  
  ReversionAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !ImportValue SubnetAId
        - !ImportValue SubnetBId
      LaunchConfigurationName: !Ref ReversionLaunchConfiguration
      MinSize: 1
      MaxSize: 2
      DesiredCapacity: 1
      Tags:
        - Key: Name
          Value: ReversionAutoScalingGroup
          PropagateAtLaunch: true

  # Need autoscaling target for reversion service
  ECSAutoScalingTargetReversion:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 2
      MinCapacity: 1
      ResourceId: !Sub "service/${NexusCluster}/ReversionService"
      RoleARN: !ImportValue NexusAutoScalingRole
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  # Set up auto scaling policy
  ECSAutoScalingPolicyReversion:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: ReversionAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ECSAutoScalingTargetReversion
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        TargetValue: 50
        ScaleInCooldown: 60
        ScaleOutCooldown: 60

Outputs:
  ClusterName: 
    Value: !ImportValue NexusCluster
    Description: Name of the ECS Cluster
  
  ServiceName:
    Value: 
      - !Ref ReversionService
    Description: Name of the ECS services
